# Site settings
title: "Uzm.Dr. İsmail BUÇGÜN • Adana Psikiyatri Uzmanı • Psikoterapist" 
description: "Adana'da özel muayenehanesinde psikiyatri ve psikoterapi alanında hizmet vermektedir. Türkiye Psikiyatri Derneğinden sertifiye destekleyici psikoterapisttir."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Uzm. Dr. İsmail BUÇGÜN"
resume_title:                   "Psikiyatri Uzmanı • Psikoterapist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "https://www.instagram.com/dr.ismailbucgun/"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "05510334896"
resume_contact_address:         "Uzm. Dr. İsmail Buçgün Muayenehanesi • Hurmalı Mahallesi Kurtuluş Caddesi No:39 Central Plaza Kat:2 Daire:23, Adana, Türkiye 01060"

resume_header_contact_info:     "Uzm. Dr. İsmail Buçgün Muayenehanesi • Hurmalı Mahallesi Kurtuluş Caddesi No:39 Central Plaza Kat:2 Daire:23, Adana, Türkiye 01060"
display_header_contact_info:    "false"

resume_header_intro: "<p><b>Adana'da özel muayenehanesinde hizmet vermektedir.</b> Muayenesinde kronik ve dirençli psikiyatrik hastalıkların ilaçla tedavisi ve takibi, bireysel destekleyici psikoterapi, bireysel psikanalitik psikoterapi, <b>Transkraniyal Manyetik Stimulasyon (TMS) ile major depresif bozukluk ve duygudurum bozukluklarının tedavisi ve takibi</b> hizmetlerini vermektedir. <b>Muayene olduktan sonra aynı binadaki anlaşmalı kurumlar aracılığı ile başka bir kuruma başvurmadan kolayca uygun fiyatlı tetkik (rutin tetkikler, ilaç kan düzeyi vb.) ve görüntüleme hizmetinden faydalanabilirsiniz.</b><br><br> Tüm psikiyatrik hastalıkların tanı ve tedavisinde klinik deneyim ve yetkinliğe sahip olmakla birlikte <b>temel mesleki ilgi alanı bipolar duygudurum bozukluğu, major depresif bozukluk ve diğer duygudurum bozukluklarıdır.</b> <b>Yaşlılık (geriatrik) psikiyatrisi, gebelik ve lohusalıktaki psikiyatrik hastalıklar</b>, nöropsikiyatri, şizofreni gibi psikotik bozukluklar ile destekleyici psikoterapi diğer mesleki ilgi alanlarıdır.<br><br>Psikiyatrik hastalıkların tedavileri için güncel tedavi kılavuzu önerilerini takip ettiği yüzlerce dirençli/kronik psikiyatrik hastalığa sahip hastadaki deneyimiyle birleştirip hastaya en uygun tedavileri uygulamaktadır.<br><br><b>Türkiye Psikiyatri Derneği tarafından sertifiye edilen bir destekleyici psikoterapi uygulayıcısıdır. Adana'da destekleyici psikoterapi uygulayıcısı olan iki psikiyatri uzmanından birisidir.</b></p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_calistigikurumlar:      true
resume_section_egitim:       true
resume_section_aldigiegitimler: true
resume_section_meslekiilgialanlari: true
resume_section_recognition:     true
resume_section_iletisimverandevu: true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "https://"
  resume_dribbble_url:          "http://"
  resume_facebook_url:          "https://facebook.com/dr.ismailbucgun/"
  resume_linkedin_url:          "http://"
  resume_youtube_url:           "http://"
  resume_spotify_url:           "http://"
  resume_instagram_url:         "https://instagram.com/dr.ismailbucgun/"
  resume_website_url:           "http://"
  resume_medium_url:            "http://"
  resume_anasayfa_url:          "https://ismailbucgun.com"
resume_print_social_links:      true

# Navigation
show_navigation: yes


# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

# Build settings
# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap

# Permalinks
permalink:      /:title

