# Site settings
title: "Uzm.Dr. İsmail BUÇGÜN"
description: "Psikiyatri Uzmanı ve Psikoterapist • Adana Dr. Ekrem Tok Ruh Sağlığı ve Hastalıkları Hastanesi"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Uzm. Dr. İsmail BUÇGÜN"
resume_title:                   "Psikiyatrist&Psikoterapist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "https://www.instagram.com/dr.ismailbucgun/"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "03222390475"
resume_contact_address:         "Adana Dr. Ekrem Tok Ruh Sağlığı ve Hastalıkları Hastanesi"

resume_header_contact_info:     "Adana Dr. Ekrem Tok Ruh Sağlığı ve Hastalıkları Hastanesi • 03222390475 "
display_header_contact_info:    "false"

resume_header_intro: "<p><b>Temel mesleki ilgi alanı bipolar duygudurum bozukluğu ve diğer duygudurum bozukluklarıdır.</b> Yaşlılık (geriatrik) psikiyatrisi, nöropsikiyatri, şizofreni ve diğer psikotik bozukluklar ile destekleyici psikoterapi diğer mesleki ilgi alanlarıdır.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_calistigikurumlar:      true
resume_section_egitim:       true
resume_section_aldigiegitimler: true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "https://"
  resume_dribbble_url:          "http://"
  resume_facebook_url:          "https://"
  resume_linkedin_url:          "http://"
  resume_instagram_url:         "https://www.instagram.com/dr.ismailbucgun/"
  resume_website_url:           "http://"
  resume_medium_url:            "http://"
  resume_anasayfa_url:          "https://ismailbucgun.com"
resume_print_social_links:      true

# Navigation
show_navigation: false
show_introduction_nav_link: false


# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

# Build settings
# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:title

