# Site settings
title: "Uzm. Dr. İsmail BUÇGÜN | Adana Psikiyatri ve TMS Kliniği" 
description: "Uzm. Dr. İsmail Buçgün, Avrupa yeterlilik belgeli bir uzman olarak Adana psikiyatri kliniğinde modern, kişiye özel ve kanıta dayalı tedaviler sunar."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Uzm. Dr. İsmail BUÇGÜN"
resume_title:                   "Psikiyatri Uzmanı"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "https://www.instagram.com/dr.ismailbucgun/"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "05510334896"
resume_contact_address:         "Uzm. Dr. İsmail Buçgün • Hurmalı Mahallesi Kurtuluş Caddesi No:39 Central Plaza Kat:6 Daire:62, Adana, Türkiye 01060"

resume_header_contact_info:     "Uzm. Dr. İsmail Buçgün • Hurmalı Mahallesi Kurtuluş Caddesi No:39 Central Plaza Kat:6 Daire:62, Adana, Türkiye 01060"
display_header_contact_info:    "false"

resume_header_intro: "<p style='text-align: justify;font-size: 1.125rem;'>Merhaba, ben <b>Dr. İsmail Buçgün!</b><br><br><b>Adana’da, özel kliniğimde psikiyatri uzmanı olarak çalışıyorum.</b><br><br>Tüm psikiyatrik hastalıkların tanı ve tedavisini kapsayan bir hizmet sunmakla birlikte, <b>özellikle bipolar bozukluk, depresyon, yineleyici depresyon, kronik depresyon ve siklotimi gibi hastalıklarla ilgileniyor ve duygudurum bozuklukları alanında çalışıyorum.</b> Ayrıca <b>yaşlılık psikiyatrisi</b> ve şizofreni gibi psikotik bozukluklar da klinik pratiğimde oldukça önemli bir yer tutuyor.<br><br>2025 Şubat ayında <b>Avrupa Psikiyatri Birliği'nin</b> <b>psikiyatride yeterlilik sınavını geçerek psikiyatri alanında Avrupa çapında kabul gören bir yeterlilik derecesi</b> anlamına gelen <b>'Fellow of the European Board of Psychiatry (Avrupa Psikiyatri Kurulu Üyesi)'</b> ünvanı aldım.<br><br>Kliniğimde, ilaç tedavisi ve psikoterapinin yanı sıra <b>Transkraniyal Manyetik Uyarım (TMS), derin TMS</b>, parlak ışık tedavisi ve gerekli durumlarda Elektrokonvülsif Terapi (EKT) gibi <b>modern ve kanıta dayalı tedavi yöntemleri</b>ne erişebiliyor ve uygulayabiliyorum. Güncel tedavi kılavuzlarını ve bilimsel literatürü, klinik deneyimimle harmanlayarak <b>kişinin durumuna özel, kanıta dayalı bir yaklaşım sunmayı hedefliyorum.</b><br><br>Türkiye Psikiyatri Derneği, Bipolar Bozukluklar Derneği, Uluslararası Bipolar Bozukluklar Derneği (ISBD), Beyin Uyarımı Akademisi (Academy of Brain Stimulation) ve Adana Tabip Odası üyesiyim.<br><br><b>Detaylı bilgi almak için aşağıdaki telefon numarası üzerinden kliniğime ulaşabilirsiniz.</b></p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_calistigikurumlar:      true
resume_section_egitim:       true
resume_section_aldigiegitimler: true
resume_section_meslekiilgialanlari: true
resume_section_recognition:     true
resume_section_iletisimverandevu: true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://"
  resume_twitter_url:           "https://"
  resume_dribbble_url:          "http://"
  resume_facebook_url:          "https://facebook.com/dr.ismailbucgun/"
  resume_linkedin_url:          "http://"
  resume_youtube_url:           "http://"
  resume_spotify_url:           "http://"
  resume_instagram_url:         "https://instagram.com/dr.ismailbucgun/"
  resume_website_url:           "http://"
  resume_medium_url:            "http://"
  resume_anasayfa_url:          "https://ismailbucgun.com"
resume_print_social_links:      true

# Navigation
show_navigation: yes


# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

# Build settings
# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap

# Permalinks
permalink:      /:title

