# Site settings
title: "Uzm.Dr. İsmail BUÇGÜN • Adana Psikiyatri Uzmanı • TMS Tedavisi" 
description: "Adana'da özel muayenehanesinde psikiyatri alanında hizmet vermektedir. TMS ve derin TMS tedavileri uygulamaktadır."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Uzm. Dr. İsmail BUÇGÜN"
resume_title:                   "Psikiyatri Uzmanı"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "https://www.instagram.com/dr.ismailbucgun/"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "05510334896"
resume_contact_address:         "Uzm. Dr. İsmail Buçgün Muayenehanesi • Hurmalı Mahallesi Kurtuluş Caddesi No:39 Central Plaza Kat:6 Daire:62, Adana, Türkiye 01060"

resume_header_contact_info:     "Uzm. Dr. İsmail Buçgün Muayenehanesi • Hurmalı Mahallesi Kurtuluş Caddesi No:39 Central Plaza Kat:6 Daire:62, Adana, Türkiye 01060"
display_header_contact_info:    "false"

resume_header_intro: "<p style='text-align: justify;font-size: 1.125rem;'>Merhaba, ben <b>Dr. İsmail!</b><br><br><b>Adana’da özel kliniğimde psikiyatri uzmanı olarak hizmet veriyorum.</b><br><br>Tüm psikiyatrik hastalıkların tanı, tedavi ve takibinde bilgi ve klinik deneyimim olsa da <b>temel olarak bipolar duygudurum bozukluğu, depresyon, tekrarlayan depresyon gibi hastalıklarla ilgileniyor ve duygudurum bozuklukları alanında çalışıyorum.</b> Buna ek olarak yaşlılık psikiyatrisi, nöropsikiyatri ve şizofreni gibi psikotik bozukluklarla da ilgileniyor ve bu alanlardaki hastalara da hizmet veriyorum.<br><br>2025 Şubat ayında <b>Avrupa Psikiyatri Birliği'nin</b> uluslararası <b>psikiyatride yeterlilik sınavını geçerek psikiyatri alanında Avrupa çapında kabul gören bir yeterlilik derecesi</b> anlamına gelen <b>'Fellow of the European Board of Psychiatry'</b> ünvanı aldım.<br><br>Psikiyatrik hastalıkların tedavisinde ilaç ve psikoterapinin yanı sıra <b><a href='/tms' title='TMS (Transkraniyal Manyetik Stimulasyon) ve Derin TMS'>Transkraniyal Manyetik Stimulasyon (TMS) ve derin TMS</a></b>, tDCS, parlak ışık tedavisi, EKT gibi yöntemlerini de uygun hastalarımda kullanıyorum. Güncel tedavi kılavuzu ve literatür önerilerini, dirençli ve tekrarlayıcı pek çok hastadan edindiğim deneyimle birleştirerek, <b>hastalarıma en uygun kanıta dayalı yaklaşımı</b> sunuyorum. <br><br>Türkiye Psikiyatri Derneği, Bipolar Bozukluklar Derneği, Uluslararası Bipolar Bozukluklar Derneği (ISBD), Beyin Uyarımı Akademisi (Academy of Brain Stimulation) ve Adana Tabip Odası üyesiyim.<br><br><b>Psikiyatrik destek almak için aşağıda yer alan telefon numarasından kliniğime ulaşabilirsiniz.</b></p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_calistigikurumlar:      true
resume_section_egitim:       true
resume_section_aldigiegitimler: true
resume_section_meslekiilgialanlari: true
resume_section_recognition:     true
resume_section_iletisimverandevu: true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "https://"
  resume_dribbble_url:          "http://"
  resume_facebook_url:          "https://facebook.com/dr.ismailbucgun/"
  resume_linkedin_url:          "http://"
  resume_youtube_url:           "http://"
  resume_spotify_url:           "http://"
  resume_instagram_url:         "https://instagram.com/dr.ismailbucgun/"
  resume_website_url:           "http://"
  resume_medium_url:            "http://"
  resume_anasayfa_url:          "https://ismailbucgun.com"
resume_print_social_links:      true

# Navigation
show_navigation: yes


# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

# Build settings
# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap

# Permalinks
permalink:      /:title

